services:
  property-search:
    image: ghcr.io/jemplayer82/property-search:latest
    ports:
      - "5050:5050"
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - results:/app/results

volumes:
  results:
